---
sudo: required

services:
  - docker

before_install:
  - docker-compose -f docker-compose-circleci.yml up -d
  - sleep 30
  - docker-compose logs

script:
    - wget http://localhost:3001 -O grafana.html
